name = "TuringPigeonsExamples"
uuid = "b301fa66-77b4-495b-9965-84baeaf1d7ef"
authors = ["Alexandre Bouchard <bouchard@stat.ubc.ca>"]
version = "0.1.0"

[deps]
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"

